### ISSUE TITLE
Command Registry

### ISSUE THREAD

**Issue by lucasilverentand** [onezerocompany/atlas#6]
Create a registry from which all the commands can be read
```[tasklist]
### Tasks
- [x] Implement base command class
- [x] Implement base command registry class
- [x] Register a command in the registry
```
